export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

export const SESSION_TOKEN = 'SESSION_TOKEN';
