export const FETCH_SHELLS_PENDING = 'FETCH_SHELLS_PENDING';
export const FETCH_SHELLS_SUCCESS = 'FETCH_SHELLS_SUCCESS';
export const FETCH_SHELLS_FAILED = 'FETCH_SHELLS_FAILED';

export const FETCH_SHELL_PENDING = 'FETCH_SHELL_PENDING';
export const FETCH_SHELL_SUCCESS = 'FETCH_SHELL_SUCCESS';
export const FETCH_SHELL_FAILED = 'FETCH_SHELL_FAILED';

export const CREATE_SHELL_PENDING = 'CREATE_SHELL_PENDING';
export const CREATE_SHELL_SUCCESS = 'CREATE_SHELL_SUCCESS';
export const CREATE_SHELL_FAILED = 'CREATE_SHELL_FAILED';

export const UPDATE_SHELL_PENDING = 'UPDATE_SHELL_PENDING';
export const UPDATE_SHELL_SUCCESS = 'UPDATE_SHELL_SUCCESS';
export const UPDATE_SHELL_FAILED = 'UPDATE_SHELL_FAILED';

export const DELETE_SHELL_PENDING = 'DELETE_SHELL_PENDING';
export const DELETE_SHELL_SUCCESS = 'DELETE_SHELL_SUCCESS';
export const DELETE_SHELL_FAILED = 'DELETE_SHELL_FAILED';
